# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '2 4,16 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: install python
        uses: actions/setup-python@v2
        with:
            python-version: '3.8' # Version range or exact version of a Python version to use, using SemVer's version range syntax
            
      - name: run script
        run: |
            /opt/hostedtoolcache/Python/3.8.6/x64/bin/python -m pip install --upgrade pip
            pip install requests
            python mimikko.py ${{ secrets.APP_ID }} ${{ secrets.AUTHORIZATION }}

      - name: push_log
        uses: seanmiddleditch/gha-publish-to-git@master
        with:
          repository: ${{ github.repository }}
          target_folder: log
          branch: master
          source_folder: log
          github_token: ${{ secrets.SECRET_TOKEN }}
